
spring.application.name=Pak_it_app
server.error.whitelabel.enabled=false

### Datasource
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.flyway.locations=classpath:/db/migration/base,classpath:/db/migration/prod
spring.flyway.out-of-order=true

### Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/

### File upload
pakit.upload-dir=./uploads/landing
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
